services:
  app2:
    container_name: busybox2
    image: busybox
    entrypoint: /bin/sh
    command: -c "while true; do echo F2 $(date +%s); sleep 5; done"
    volumes:
        - data:/test-data/data2

volumes:
  data:
