services:
  app2:
    container_name: busybox2
    image: busybox
    entrypoint: /bin/sh
    command: -c "while true; do echo F2 $(date +%s); ls -la /test-data; sleep 5; done"
    volumes:
        - data:/test-data

volumes:
  data:
